version: '3.8'

services:
  n8n:
    build: .
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
     # Add your environment variables here
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=lim6112
      - N8N_BASIC_AUTH_PASSWORD=gogosin0
      - YOUTUBE_API_KEY=AIzaSyDrLa0FaHc3r2NNQm_QBoXTw3iM4dxEANo
      - NODE_FUNCTION_ALLOW_EXTERNAL=axios,node-fetch,iso8601-duration,langfuse-langchain,langchain,@langchain/core
      - N8N_NODE_MODULES_INCLUDE_LIST=langfuse-langchain,langchain,@langchain/core
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      # - WEBHOOK_URL=https://draven-reparative-subfestively.ngrok-free.dev
      # Add more variables as needed
      # - CUSTOM_VAR=value
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./files:/home/node/files
